# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'test-sp'
    subscriptionId: 'c3bffe7f-e643-4393-ae69-ab6e9fd0668f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-ls-prasanga-banerjee'
    location: 'West US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Prasanga1996/plug/main/CreateStorage/Storage.json'
    overrideParameters: |
      -storageAccountName newstorage
      -location West US
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'